name: Build Typst Documents

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Typst
        uses: typst-community/setup-typst@v3
      
      - name: Create dist directory
        run: mkdir -p dist
      
      - name: Build all documents
        run: ./build.sh

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documents
          path: dist/*.pdf
          overwrite: true
